### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by suprafun** [lou1306/localpathplanner#1]
Hello, under what license is this project released under ? I would like to study it to learn from it. Thank you.

**Comment by lou1306** [comment]
Thank you for your interest.
This repository is MIT-licensed. I have added a LICENSE file to clarify that. You can find some details on how the project works under the docs/ directory (some files are only in Italian, though).

Just a courtesy. If your study results in any kind of publication, please add a reference to the following extended abstract:

L. Di Stefano, E. Clementini, and E. Stagnini, “Reactive Obstacle Avoidance for Multicopter UAVs via Evaluation of Depth Maps,” in Proceedings of Workshops and Posters at the 13th International Conference on Spatial Information Theory (COSIT), L’Aquila, Italy, Sep. 2017, pp. 41–43, doi: 10.1007/978-3-319-63946-8_10. URL: https://link.springer.com/chapter/10.1007%2F978-3-319-63946-8_10
